# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#

User.destroy_all
Course.destroy_all
CourseSession.destroy_all
Review.destroy_all
Message.destroy_all
Category.destroy_all
CourseSession.destroy_all

#***** Test Account ***************************
@Joseph = User.create!(first_name: "Joseph", last_name: "Arias", email: "guest@guest.com", password: 'guest', bio: "Salsa and bachata dancer and instructor" , image: "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/17903340_1494075703959081_7689354803625661275_n.jpg?_nc_cat=100&_nc_ht=scontent-iad3-1.xx&oh=d0e7db040b8004e07c953c4ea6796b26&oe=5CBAC918")
#**********************************************

@Liz = User.create!(first_name: "Liz", last_name: "Orellana", email: "liz@gmail.com", password: '123', bio: "I love to travel and explore new hobbies", image: "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/46449267_10217886486896539_5240317790014930944_n.jpg?_nc_cat=103&_nc_ht=scontent-iad3-1.xx&oh=baf3da55aaa17b95a3e3e98bbfe9b3f5&oe=5CC6B031")
@Anna = User.create!(first_name: "Anna", last_name: "Conaway", email: "anna@gmail.com", password: '123', bio: "Fluent in French and in my spare time I like to explore the different flavors in wine", image: "https://miro.medium.com/fit/c/240/240/1*xqYC2dILKcK6jKGzUg-7hA.jpeg")
@Mike = User.create!(first_name: "Mike", last_name: "Kim", email: "mike@gmail.com", password: '123', bio: "Former collegiate athlete and active professional lacrosse player", image: "https://miro.medium.com/fit/c/240/240/0*EehIf4cq_fyYVL7I")
@Ana = User.create!(first_name: "Ana", last_name: "Harris", email: "ana@gmail.com", password: '123', bio: "Dancer, Traveler and language lover", image: "https://avatars1.githubusercontent.com/u/37843405?s=460&v=4")
@Lane = User.create!(first_name: "Lane", last_name: "Miller", email: "lane@gmail.com", password: '123', bio: "Former gold metal champion in Super Mario", image: "https://avatars2.githubusercontent.com/u/35706746?s=460&v=4" )
@Hillary = User.create!(first_name: 'Hillary', last_name: "Scofield", email: "hillary@gmail.com", password: "123", bio: "Developer by day and comedian by night", image: "https://avatars2.githubusercontent.com/u/32621623?s=460&v=4")
@Beth = User.create!(first_name: "Beth", last_name: "Wilson", email: "beth@gmail.com", password: "123", bio: "Musician, Teacher and latin music lover", image: "https://avatars2.githubusercontent.com/u/40366958?s=460&v=4")
@Marissa = User.create!(first_name: "Marissa", last_name: "McHugh", email: "marissa@gmail.com", password: "123", bio: "Food lover, traveler and marathon runner", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR8W8Igt1HK7pXW_zrFagvtXJHEvzkEo53o7KOUDPNV1Ci3E7FEg")
@Jennifer = User.create!(first_name: "Jennifer", last_name: "Ingram", email: "jennifer@gmail.com", password: "123", bio: "Fine Arts Teacher with 23 years experience, specializing in watercolor and oil painting, figure, and live drawing", image: "https://pbs.twimg.com/profile_images/830988951229911040/zERKKw2o_400x400.jpg")
@Moses = User.create!(first_name: "Moses", last_name: "Mbemba", email: "moses@gmail.com", password: "123", bio: "I am a 22 year old dancer. I have been dancing since I was four years old. I have been actually instructing dance a little over seven years now. I teach any where from beginner to advanced hip hop.", image: "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/1937060_10153603272169091_6035583180075354138_n.jpg?_nc_cat=103&_nc_ht=scontent-iad3-1.xx&oh=daf5ca71c4701b1af452dcc2ae31c563&oe=5CCCF0F7")
@Karine = User.create!(first_name: "Karine", last_name: "Rios", email: "karine@gmail.com", password: "123", bio: "I am a certified, experienced foreign language with more than 24 years. I have taught multilevel courses in Spanish Portuguese and Hebrew in DC and in the State of Florida.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxA_06yI8TnkR8OXzLA0z1BsuAEdbTtWLi7a-fBSFROp4mXXWl")
@Andrew = User.create!(first_name: "Andrew", last_name: "Rivera", email: "andrew@gmail.com", password: "123", bio: "Musician by choice and software developer by chance: I don't have any formal education in music but I've been playing guitar for almost 15+ years now. Played with many bands and many venues.", image: "https://avatars3.githubusercontent.com/u/37312269?s=460&v=4")
@William = User.create!(first_name: "William", last_name: "Sanchez", email: "william@gmail.com", password: "123", bio: "I teach classes of salsa, bachata and kizomba and more. Cadence, technique, connection and fun, dare and know yourself through dancing", image: "https://i1.wp.com/www.dccasineros.org/wp-content/uploads/2015/06/williamhead400px.jpg?fit=400%2C400")
@Tracy = User.create!(first_name: "Tracy", last_name: "Perez", email: "tracy@gmail.com", password: "123", bio: "A born and raised native Filipina from the Philippines, but currently living in California.", image: "https://pbs.twimg.com/profile_images/453026769080025089/xhba6eb4_400x400.jpeg")
@Ann = User.create!(first_name: "Ann", last_name: "Duong", email: "ann@gmail.com", password: "123", bio: "I am a trained film/TV makeup artist, which means I have to be able to create a Full-look, including doing salon-quality manicures and pedicures. I learned the science behind how your nails grow and become healthy as well as how to promote it.", image: "https://avatars3.githubusercontent.com/u/39737217?s=460&v=4")
@Sami = User.create!(first_name: "Sami", last_name: "Ahmed", email: "sami@gmail.com", password: "123", bio: "dancer, choreographer and dance instructor for over 10 years. I performed and taught in some of the most recognised Latin Dance events in Brazil and around the world", image: "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/983605_10160174061385361_2352495470940807931_n.jpg?_nc_cat=106&_nc_ht=scontent-iad3-1.xx&oh=3e3df8b72f540a13bf900931e205ffe8&oe=5CD2686D")
@Brad = User.create!(first_name: "Brad", last_name: "Gordon", email: "brad@gmail.com", password: "123", bio: "I have been involved in residential repairs and remodeling for over 30 years. While not a licensed contractor, I do flip houses on a full time basis.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT412624HZjwleFhdD8jDNusSTPHBo4VtZnz9CasPLZQkUZ7_qoSg")
@Alejandra = User.create!(first_name: "Alejandra", last_name: "Salvatierra", email: "alejandra@gmail.com", password: "123", bio: "I am a professional tattoo artist and piercer. Currently a sophomore in college as well getting my degree in fine arts in preparetion for teaching.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDv66MF_pYYQ4HZ02nXzo9NiE6qt50i8h2CWu7XcH3Si6d8C4x8g")
@Hokuto = User.create!(first_name: "Hokuto", last_name: "Konishi", email: "hokuto@gmail.com", password: "123", bio: "Born in Tokyo, I started dancing at age 13. I also like to cook, draw, paint, design, and play the violin.", image: "https://static1.squarespace.com/static/543c7d46e4b08e14ea35e665/t/54ecf4b6e4b0c01a6f3aa066/1424815298802/feng+justfeng+ryan+hok+hokuto+konishi+quest+crew+hair+photography")
@Cassidy = User.create!(first_name: "Cassidy", last_name: "Lape", email: "cassidy@gmail.com", password: "123", bio: "Have completed 5 years of ASL classes. Working on my Interpreting Degree at RIT.", image: "https://dcmp.org/images/learning_center/366/Ashlea%20Hayes.jpg")
@Yihan = User.create!(first_name: "Yihan", last_name: "lee", email: "yihan@gmail.com", password: "123", bio: "Tutor of Chinese and English since 2008, I have developed different fun and educational methods adapted to different age levels and with different needs.", image: "https://www.sas.rochester.edu/psy/people/gradstudents/li_yihan/assets/images/yihanli.jpg")
@Emerson = User.create!(first_name: "Emerson", last_name: "Morales", email: "emerson@gmail.com", password: "123", bio: "I always had a passion for all things music and dance related." , image: "https://scontent-lhr3-1.cdninstagram.com/vp/4be42323c8179acc5e26c41430755781/5C8EAB47/t51.2885-15/e35/46880121_312284986053158_2789795220493957859_n.jpg?_nc_ht=scontent-lhr3-1.cdninstagram.com&se=7&ig_cache_key=MTkzMjI0OTc5MDU0MTAzNzc1Mg%3D%3D.2" )


#*** COURSES ***************************************

@Course1 = Course.create!(name: "Salsa Dancing", description: "Salsa dancing is always excellent entertainment. It also helps in building a lot of energy and hence is a good way to start your day. You may learn salsa dancing in the privacy of your house or in a studio, with or without a partner and it is also a fitness program that can readily be integrated into your social life.", image: "https://scontent-iad3-1.xx.fbcdn.net/v/t31.0-8/12909588_10209534333383299_2886464381534572286_o.jpg?_nc_cat=110&_nc_ht=scontent-iad3-1.xx&oh=88e6caeb92e82d0ee8eb0995ea54098b&oe=5C8CDDCF", bio: "I've been salsa dancing for 4 years and I know how to dance salsa on1 and on2 and casino.", instructor_id: @Joseph.id, city: "DC", address: "801 9th St NW suite a, Washington, DC 20001", hourly: 38)

@Course2 = Course.create!(name: "Wine Tasting", description: "I will provide essential education on wine. I will help train your sense of smell, taste and touch and then apply that training through a tasting evaluation. This combination of sensual training and theoretical knowledge will set a foundation for life-long learning about wine.", image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "6 years of experience in the wine industry includes retail ownership, as well as retaurant and wholesale management", instructor_id: @Anna.id, city: "DC", address: "777 6th St NW, Washington, DC 20001", hourly: 40)

# @Course3 = Course.create!(name: "Lacrosse Training", description: "Spent the last five years, including the past two seasons as a midfielder for the DC blueSkins lacrosse team. Specialties: transistion, shooting, passing, protecting, speed, endurance", image: "https://laxallstars.com/wp-content/uploads/2016/06/LAS_TRILOGY-SPRING-TRAINING-3-760x507.jpg", bio: "Former collegiate athlete and active professional lacrosse player and coach", instructor_id: @Mike.id, city: "DC", address: "1509 16th Street, NW, Washington, DC 20036")

@Course4 = Course.create!(name: "Ballroom dancing", description: "On your own or with a partner or friend, whether you’re a beginner or a seasoned professional, whether you want to meet new friends while learning basic skills or train for competition, I can help develop your ballroom dancing by a customized lesson plan. Each lesson will be tailored to your needs, interests and desires. With a focus on technique, rhythm, and partnering skills, I will give you the confidence to dance well in any social setting.", image: "https://static1.squarespace.com/static/51437aa1e4b04eaef3678abd/t/55bafb8ae4b08c22e013f05d/1438317450619/teaching_duet1.jpg?format=1500w", bio: "I will personalize each dance lesson based on your individual needs, desires, and goals, adjusting our teaching style to your ability, personality, and expectations. This ensures the most thorough and rapid learning process, all while keeping it fun, easy, and comfortable.", instructor_id: @Ana.id, city: "DC", address: "5207 Wisconsin Ave, Washington, DC 20015", hourly: 40)

# @Course5 = Course.create!(name: "Pro Gaming Training", description: "My method of teaching is relaxed friendly and go with the flow. Despite this, I will spend every moment teaching you something to help improve. But most importantly my goal in teaching is to teach you not just a specific skill for a specific game, but skills for multiple games. So you can pick up any game and have a solid base. Lessons usually consist of live game analysis, replay analysis, or jumping into custom games with your coach so they can give you tips, tricks, and strategies to help you win more!", image: "https://cdn.dotablast.com/wp-content/uploads/2015/06/evil-geniuses-esl-one.jpg", bio: "Former gold metal champion in Super Mario", instructor_id: @Lane.id, city: "DC", address: "645 Pennsylvania Ave SE, Washington, DC 20003")

@Course6 = Course.create!(name: "Stand Up Comedy", description: "Stand-up comedy is a fantastic art form and once you start digging, you realize the possibilities are endless. In the words of my comedy mentor, “The beauty of stand-up is that all you need is a light, a chair, and a microphone so you can take it with you wherever you go.", image: "https://images.unsplash.com/photo-1468390090990-afe21a9448f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1335&q=80", bio: "Originally from New Zealand, I'm an actor, comedian and acting coach.", instructor_id: @Hillary.id, city: "DC", address: "1140 Connecticut Ave NW, Washington, DC 20036", hourly: 38)

@Course7 = Course.create!(name: "Hip-hop and Breakdance", description: "Hip-hop dance is a dynamic and improvisational dance style with jumps, freezes, isolations, and rotations in movement. Hip hop helps dancers to improve flexibility, strength, coordination, and endurance all while keeping dancers engaged and challenged. I teach private lessons for all ages and all levels. The class could be in a public place like a cultural center or at the student´s home. Alone or with several people, I will adapt the class to your level, schedule and needs.", image: "https://images.unsplash.com/photo-1527256285774-3361536b165d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1055&q=80", bio: "I am a professional dancer, performer and dance teacher. In love with movement, music and dance. I consider myself an endless student, devote to daily practice. I study every dance that I can and different arts of movement.", instructor_id: @Moses.id, city: "DC", address: "3225 8th St NE, Washington, DC 20017", hourly: 38)

@Course8 = Course.create!(name: "Brazilian portuguese lessons", description: "Experiencing first hand the similarities and differences of each individual language structure, I relate well to my students and do give them the necessary skills to become fluent in the target language. In the past few years my students have participated in the National spanish and Portuguese contest throughout the DC Metropolitan area and receive honorable mentions and high recognitions.", image: "https://images.unsplash.com/photo-1527374071603-76de89807336?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1055&q=80", bio: "Being born and raised in Brazil till the age of 15, I was exposed to three different languages while growing. I became interested in language acquisition and determined to pursue my studies in foreign languages and education.", instructor_id: @Karine.id, city: "DC", address: "1030 15th St NW, Washington, DC 20005", hourly: 38)

@Course9 = Course.create!(name: "Guitar Lessons", description: "The cornerstone of my teaching method is improvisation. I progressively add bricks of knowledge to expand the musical playground. I compose pieces (all styles) centered around particular theoretical concepts, and encourage students to add their own modifications as they go. I have had multiple teachers in my life, in multiple countries, each with their own method. However I firmly believe that the best possible teacher is ones self. This is the goal of my method: to teach you how to teach yourself.", image: "https://images.unsplash.com/photo-1525204016358-717c1c37382f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "Played with a lot of amazing musicians at many unique venues. I have had many students from beginner to advance. It mostly comes down to what they are interested in learning and based on that I form my teaching style.", instructor_id: @Andrew.id, city: "DC", address: "604 U St NW, 3rd floor, Washington, DC 20001", hourly: 40)

@Course10 = Course.create!(name: "Home Repairs", description: "I am a laid back presenter, I will create a lesson to teach you how to complete a project from start to finish. I will come to your location. I will explain what materials and tools you will need and where to purchase them. While tutoring I prefer to have it student lead and just help to point to the student in the right direction. In that case the student learns the knowledge for themselves and it is not just handed to them.", image: "https://images.unsplash.com/photo-1536746262157-60876e2dd287?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=937&q=80", bio: "I have worked in housing industry for more than 7 years as a carpenter and owning a home repair business. I can teach you basic pluming, electrical, and carpentry so that you can do your own remodeling and repairs.", instructor_id: @Joseph.id, city: "DC", address: "E, Washington, DC 20036", hourly: 45)

@Course11 = Course.create!(name: "Figure Drawing", description: "My lesson are a combination of many modalities, including hands on projects, reading silently and aloud. modeling, guided practice, differentiated instruction based on a brief learning style survey. Art lessons are based on student choice and media selection catered to the skill level. During our one hour session, we will explore using a variety of methods to keep the lessons flowing.", image: "https://images.unsplash.com/photo-1535450185859-99bc15f70e76?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I have been teaching for over 25 years. In that time, I have tutored and worked with small groups. I have taught hundreds of students during that time ( I really never kept count).", instructor_id: @Jennifer.id, city: "DC", address: "2129 S St NW, Washington, DC 20008", hourly: 40)

@Course12 = Course.create!(name: "Bachata Dancing", description: "My classes are trully focused on the social dance, where I give my students all the tips and tools,so that they can defend themselves and enjoy themselves on a dance floor, be it a party, a romantic date with their couple, marriages or any celebration. They are based on evaluating the student's weaknesess and sthengths, to develop a study plan, starting from the postures, control and coordination of the body, specific exercises and supervised repetitions at all times.", image: "https://images.unsplash.com/photo-1474308305481-198184645d10?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "Instructor of Latin Dances, specialized in Salsa, Casino, Merengue, Bachata and Kizomba, with more than 10 years of experience, dedicated and willing to help young people, adults and seniors who know nothing at all about dancing, to achieve their dreams and personal goals.", instructor_id: @William.id, city: "DC", address: "999 9th St NW, Washington, DC 20001", hourly: 38)

@Course13 = Course.create!(name: "Learn How to Speak Tagalog", description: "I always start from the simplest way and the most basic words that I can teach to my students. I usually share my knowledge to other races who wanted to learn Tagalog and as well as to younger generations with a Filipino blood but born and raised here in the United States and are also willing to learn their native language. In this way, they can easily communicate to their Filipino peers.", image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I was born and raised in the Philippines for 17 years. I am also an immigrant, so my parents and I are currently living in Washington DC. Back when I was still studying from my country, I got to learn different aspects of our language, which is Filipino but well-known as Tagalog.", instructor_id: @Tracy.id, city: "DC", address: "1717 Rhode Island Ave NW, Washington, DC 20036", hourly: 38 )

@Course14 = Course.create!(name: "Piano Lessons", description: "Every person learns differently. My goal is to teach based on the individual's preference. I do believe that repetition is the mother of skill. I encourage my students to spend a good amount of time practicing as that is the best way to build muscle memory.", image: "https://images.unsplash.com/photo-1519076976365-9c64dbd98317?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1041&q=80", bio: "I have been playing piano for over 10 years, wrote countless songs. and perform regularly at a local coffee shop. I am proud to pass on my musical skill to other people and would be more than happy to pass it on to you.", instructor_id: @Beth.id, city: "DC", address: "3287 M St NW, Washington, DC 20007", hourly: 40)

@Course15 = Course.create!(name: "Getting Started in Woodworking", description: "My teaching method is a hands on type physically give a description if possible that way you get a visual and not having to second guess yourself. My teaching method usually starts with me starting the days lesson or topic and then letting the students and discussion lead the way with me as moderator. While tutoring I prefer to have it student lead and just help to point to the student in the right direction.", image: "https://images.unsplash.com/photo-1473621038790-b778b4750efe?ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80", bio: "Carpenter offering General maintenance and Building strategies in DC with 18 years of experience", instructor_id: @William.id, city: "DC", address: "935 Brentwood Rd NE, Washington, DC 20018", hourly: 40)

@Course16 = Course.create!(name: "Nail Art", description: "I believe hands-on practice, clear explanation and straight forward demonstration is the best way to learn. I always want people to know the reasoning behind the things I teach them. Teaching is not just about the content , but how information is delivered to make learning fun and memorable . Each lesson will start with a brief Q&A, so that we might utilize our time together focusing on areas you specifically want to cover .", image: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I have 20 years experience in the Beauty Field. My main focus has been Makeup. After working As a glam Makeup artist in a photo studio for 15 years I went of to become a beauty consultant Teaching people how to apply make-up as well as skin care products", instructor_id: @Ann.id, city: "DC", address: "1010 Massachusetts Ave NW, Washington, DC 20001", hourly: 45)

@Course17 = Course.create!(name: "Zouk Dance", description: "Zouk is a partner dance originating from Brazil. Also known as zouk-lambada, the dance is a descendant of the late 1980's hit music & dance, lambada. Brazilian zouk is characterized by the dancers’ undulating bodies and the girls' flowing hair. Depending on the style of Brazilian zouk, you can see a close connection embrace and long graceful steps, strong hip movements, body isolations and upper-body torsions, wild spins and whip-like head movements.", image: "https://www.danceinforma.com/wp-content/uploads/2015/03/ShannonCronynZouk-TIPDI-workshop.jpg", bio: "I'm a Zouk instructor and DJ from Brasilia, Brazil. My style of teaching focuses on slow, soulful zouk movements in concert with musicality and partner connection.", instructor_id: @Sami.id, city: "DC", address: "2201 P St NW, Washington, DC 20037", hourly: 40)

@Course18 = Course.create!(name: "Start speaking French", description: "For beginners I first approach the sounds of French to quickly begin to learn the different times of the language. My goal is to quickly put the student at ease so that we can train to talk by imagining different situations or by exchanging our opinions on different subjects. I approach tutoring as a custom-made session. I listen to my students, learn about their learning styles, and tailor lessons to meet their needs and wants. My goal is to instill the love of learning a foreign language, and to help them achieve what they want.", image: "https://images.unsplash.com/photo-1530019084464-d4d90a929895?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I have a degree in French and English and 8 years experience in speaking, reading, learning, and writing French. My passion for teaching and helping others learn French is easy to see.", instructor_id: @Anna.id, city: "DC", address: "1401 Pennsylvania Ave NW, Washington, DC 20004", hourly: 38)

@Course19 = Course.create!(name: "Music Production", description: "I always try and ask student's what music they like and if what style, genres, songs or artists they they are interested in learning. Based on that I try to build a curriculum in a way that I can teach production and composition techniques. This helps the student knowledge and understanding grow, as well as keeps the student engaged and interested. My aim to bring a student to level where they can self teach themselves along with gathering and practicing new material.", image: "https://images.unsplash.com/photo-1525009901332-a69f4c0d3efe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "Music Producer and Composer. Working as a musician for over 7 years. Graduate from Berklee College of Music", instructor_id: @Andrew.id, city: "DC", address: "1455 Pennsylvania Ave NW #400, Washington, DC 20004", hourly: 38)

@Course20 = Course.create!(name: "Blacksmith training", description: "Student will find a mix of theory and hands-on projects. They will learn forge welding, hot carving, tool making, cutting and much more. They will also gain the experience to create a variety of metal products, including custom railings, hardware, furniture, garden décor, and home decoration/art. Beside technical ability and practical skills, student will gain good hand-to-eye coordination, problem-solving skills, math skills for measuring and making precise cuts and calculations, and creative and design skills.", image: "https://images.unsplash.com/photo-1497369573176-0ceb5353817d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1053&q=80", bio: "My formal schooling is in gunsmithing, which gives me an eye and skill for detail and precision. I also have worked as a carpenter which helps in designing structural ironwork and working with building codes.", instructor_id: @Brad.id, city: "DC", address: "1111 19th St NW, Washington, DC 20036", hourly: 40)

@Course21 = Course.create!(name: "Draw like a tattoo artist", description: "I will teach you what you need to know about designing a piece of art that will actually translate to skin. I believe in giving a common goal and letting students flourish their own creativity.", image: "https://images.unsplash.com/photo-1501577045883-a881de2cf176?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1192&q=80", bio: "I am a professional tattooer I have been tattooing at award winning shops across the USA. I have 8 years of experience in the industry. I have been drawing since I could pick up a pencil.", instructor_id: @Alejandra.id, city: "DC", address: "1333 Connecticut Ave North West, 3rd floor, Washington, DC 20036", hourly: 40)

@Course22 = Course.create!(name: "Tutting", description: "Through my expertise, I can immediately classify my students' level and adjust my lesson content as well as the tempo accordingly. I have had over 20 years of intensive dance lessons. Therefore, I see exactly why, for example, a movement does not work or does not look good and can offer assistance in various ways. I am very patient and have never experienced a student leaving my class frustrated or dissatisfied.", image: "https://images.unsplash.com/photo-1530354359846-eab3792396ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I am a freelance dancer, dance teacher and choreographer. At the age of 21, I set out on my own, in addition to my knowledge of classical ballet and contemporary dance, to acquire various hiphop styles myself, such as popping and tutting.", instructor_id: @Hokuto.id, city: "DC", address: "1333 H St NE, Washington, DC 20002", hourly: 35)

@Course23 = Course.create!(name: "Sign Language", description: "My classes would be for anyone interested in learning ASL as well as for people in ASL classes that need some extra help with topics. I approach teaching by finding out where my students are at and bring them to their fullest potential. I will base my lessons off of what you are looking to learn about. I will also do my best to reteach lessons thought by another teacher if needed for clarifications.", image: "https://images.unsplash.com/photo-1524964056700-f5738231ad5e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I am an interpreting student at RIT. I have been studying ASL for 5 years. I am currently a teachers assistant at doodle bugs, It is truly a passion of mine to teach children. I love teaching my friends and family Sign so I would truly enjoy teaching others.", instructor_id: @Cassidy.id, city: "DC", address: "2100 M street NW 170, Washington, DC 20037", hourly: 40 )

@Course24 = Course.create!(name: "Percussion Drums", description: "Course pace West African (Djembe, dununs, Karignan), Afro-Brazilian (atabaques, Agogo etc. ..) Afro-Caribbean (congas, claves, bells etc ...) Oriental (Darbuka). Pedagogy adapted to the European public but based on African and Caribbean bases. Working from first principles. Work of improvisation. Training from beginner to professional. Instruments provided for beginners.", image: "https://images.unsplash.com/photo-1537930385926-b88db6f104a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "Professor for over 10 years. Professor in the voluntary sector, in music schools. Visiting Lecturer for Education & the Ministry of Justice. Training hundreds of students (beginners, intermediate or advanced, professional, children, teenagers, adults) as part of courses and internships.", instructor_id: @Sami.id, city: "DC", address: "1506 North Capitol St NW, Washington, DC 20002", hourly: 35)

@Course25 = Course.create!(name: "Learn to Build a Tiny Home", description: "Learn what it takes to design your own home. Find out how to leverage the work of others to keep design costs down while getting the exact house you want. Learn the details required to do the actual building. This includes building the walls, roof, drying-in the house, installing the windows and doors, siding, roofing material, and so on.", image: "https://bloximages.chicago2.vip.townnews.com/wataugademocrat.com/content/tncms/assets/v3/editorial/5/ed/5ed638e8-90bd-5c5d-bcc5-4fabf2d0dafe/5b483f3e2826a.image.jpg?resize=1200%2C800", bio: " I been a professional builder for over 20+ years but my passion and focus is on empowering others. I have taught over 1000 students at my workshops and have seen, time and time again, people with no previous building experience create the home of their dreams.", instructor_id: @Marissa.id, city: "DC", address: "21 Evarts St NE, Washington, DC 20002", hourly: 50)

@Course26 = Course.create!(name: "Digital Photography Lessons", description: "My way of teaching depends on your level. In general I avoid doing too much theory, i'd rather train you, sitting next to you on a second computer. I teach the technical and artistic sides of photography together. I can teach portrait, event, nature and abstract photography. I specialize in using natural light, but I can also teach studio lighting and flash photography. My classes are fun and relaxed!", image: "https://images.unsplash.com/photo-1541516160071-4bb0c5af65ba?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I have a Bachelor's of Fine Arts in Photography and over 3 years experience teaching adults and youth. I have been running my freelance photography business for 5 years and can help my students start their own careers.", instructor_id: @Ana.id, city: "DC", address: "1200 N St NW APT 110, Washington, DC 20005", hourly: 38)

@Course27 = Course.create!(name: "Learning Chinese", description: "My teaching experience allows me to establish a good curriculum quickly with students and adopt the best teaching methods by drawing on the curriculum. All the pupils I taught have progress in the corresponding subjects. I have already given courses of Chinese, English or French as a foreign language to students of different ages (from 3 years to 40 years)", image: "https://images.unsplash.com/photo-1463319611694-4bf9eb5a6e72?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I offer Chinese, English and French as a foreign language courses to students of all levels at IRIS Education (IDF). I know the Chinese, American and French education system well, so I can communicate knowledge to students according to their differences in aptitude and intelligence.", instructor_id: @Yihan.id, city: "DC", address: "1629 K St NW #300, Washington, DC 20006", hourly: 38)

@Course28 = Course.create!(name: "Learn to be a DJ", description: "I offer customized courses for amateurs who want to get or improve in exciting activities that are the Mix / DJ and production / MAO. You choose if you want to become a DJ, producer / composer or both like me. My teaching methods are simple and have already proven themselves. We will work according to your favorite musical styles. We will greatly practice with exercises and set custom status already approved by former students.", image: "https://images.unsplash.com/photo-1494214838014-b52af3638ee4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80", bio: "I teach for 4 years. I've trained a dozen students including one that is currently resident DJ in DC. Being passionate about my business and teaching, my most is that I can communicate this enthusiasm and motivate my students to arrive at the final by themselves to achieve their goals.", instructor_id: @Emerson.id, city: "DC", address: "1339 V St NW, Washington, DC 20009", hourly: 38)

@Course29 = Course.create!(name: "Patio/floor", description: "Incorporate a hard-surface floor into a garden area to make an instant room. Flooring gives furniture firm footing as well. Building a flagstone patio is much like putting together a puzzle. Rotate the pieces until they fit together, working to create nearly uniform space between the stones. Students will learn how to build a flagstone, brick, or paver patio.", image: "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2007/7/5/0/HDSWT-210_StonePatio_layout.jpg.rend.hgtvcom.1280.960.suffix/1400940183965.jpeg", bio: "My formal schooling is in gunsmithing, which gives me an eye and skill for detail and precision. I also have worked as a carpenter which helps in designing structural ironwork and working with building codes.", instructor_id: @Brad.id, city: "DC", address: "1415 22nd St NW #64, Washington, DC 20037", hourly: 45)



#*** COURSE SESSIONS ***************************************

@CourseSession1 = CourseSession.create!(checkin: DateTime.new(2018, 6, 22), checkout: DateTime.new(2018, 9, 10), student_id: @Liz.id, course_id: @Course1.id)
@CourseSession2 = CourseSession.create!(checkin: DateTime.new(2018, 5, 22), checkout: DateTime.new(2018, 10, 10), student_id: @Beth.id, course_id: @Course1.id)

#*** REVIEWS ***************************************

@Review1 = Review.create!(description: "Joseph was a great instructor! I had a great time", rating: 5, student_id: @Liz.id, course_session_id: @CourseSession1.id)
@Review2 = Review.create!(description: "Great music, Great people, Great time!", rating: 5, student_id: @Beth.id, course_session_id: @CourseSession2.id)


#*** MESSAGES ***************************************

@Message1 = Message.create!(content: "Do you teach bachata too?", sender_id: @Liz.id, recipient_id: @Joseph.id )
@Message2 = Message.create!(content: "Do you teach salsa too?", sender_id: @Beth.id, recipient_id: @Joseph.id )

#*** CATEGORIES ***************************************

@Category1 = Category.create!(name: "Dancing")
@Category2 = Category.create!(name: "Languages")
@Category3 = Category.create!(name: "Musical")
@Category4 = Category.create!(name: "Carpentry")
@Category5 = Category.create!(name: "Art")


#*** COURSE CATEGORIES ***************************************

# Dancing
@CourseCategory1 = CourseCategory.create!(course_id: @Course1.id, category_id: @Category1.id)
@CourseCategory6 = CourseCategory.create!(course_id: @Course4.id, category_id: @Category1.id)
@CourseCategory3 = CourseCategory.create!(course_id: @Course7.id, category_id: @Category1.id)
@CourseCategory10 = CourseCategory.create!(course_id: @Course12.id, category_id: @Category1.id)
@CourseCategory15 = CourseCategory.create!(course_id: @Course17.id, category_id: @Category1.id)
@CourseCategory20 = CourseCategory.create!(course_id: @Course22.id, category_id: @Category1.id)

# Languages
@CourseCategory4 = CourseCategory.create!(course_id: @Course6.id, category_id: @Category2.id)
@CourseCategory5 = CourseCategory.create!(course_id: @Course8.id, category_id: @Category2.id)
@CourseCategory11 = CourseCategory.create!(course_id: @Course13.id, category_id: @Category2.id)
@CourseCategory16 = CourseCategory.create!(course_id: @Course18.id, category_id: @Category2.id)
@CourseCategory21 = CourseCategory.create!(course_id: @Course23.id, category_id: @Category2.id)
@CourseCategory25 = CourseCategory.create!(course_id: @Course27.id, category_id: @Category2.id)

# Musical
@CourseCategory7 = CourseCategory.create!(course_id: @Course9.id, category_id: @Category3.id)
@CourseCategory12 = CourseCategory.create!(course_id: @Course14.id, category_id: @Category3.id)
@CourseCategory17 = CourseCategory.create!(course_id: @Course19.id, category_id: @Category3.id)
@CourseCategory22 = CourseCategory.create!(course_id: @Course24.id, category_id: @Category3.id)
@CourseCategory26 = CourseCategory.create!(course_id: @Course28.id, category_id: @Category3.id)


# Carpentry
@CourseCategory8 = CourseCategory.create!(course_id: @Course10.id, category_id: @Category4.id)
@CourseCategory13 = CourseCategory.create!(course_id: @Course15.id, category_id: @Category4.id)
@CourseCategory18 = CourseCategory.create!(course_id: @Course20.id, category_id: @Category4.id)
@CourseCategory23 = CourseCategory.create!(course_id: @Course25.id, category_id: @Category4.id)
@CourseCategory27 = CourseCategory.create!(course_id: @Course29.id, category_id: @Category4.id)


# Art
@CourseCategory2 = CourseCategory.create!(course_id: @Course2.id, category_id: @Category5.id)
@CourseCategory9 = CourseCategory.create!(course_id: @Course11.id, category_id: @Category5.id)
@CourseCategory14 = CourseCategory.create!(course_id: @Course16.id, category_id: @Category5.id)
@CourseCategory19 = CourseCategory.create!(course_id: @Course21.id, category_id: @Category5.id)
@CourseCategory24 = CourseCategory.create!(course_id: @Course26.id, category_id: @Category5.id)





